// clang-format off
/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode v1 to v2

    This file was automatically generated by CANopenEditor v4.0-104-g6f50f73

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
*******************************************************************************/
#ifndef CO_OD_H_
#define CO_OD_H_

/*******************************************************************************
   CANopen DATA TYPES
*******************************************************************************/
   typedef bool_t       BOOLEAN;
   typedef uint8_t      UNSIGNED8;
   typedef uint16_t     UNSIGNED16;
   typedef uint32_t     UNSIGNED32;
   typedef uint64_t     UNSIGNED64;
   typedef int8_t       INTEGER8;
   typedef int16_t      INTEGER16;
   typedef int32_t      INTEGER32;
   typedef int64_t      INTEGER64;
   typedef float32_t    REAL32;
   typedef float64_t    REAL64;
   typedef char_t       VISIBLE_STRING;
   typedef oChar_t      OCTET_STRING;

   #ifdef DOMAIN
   #undef DOMAIN
   #endif

   typedef domain_t     DOMAIN;


/*******************************************************************************
   FILE INFO:
      FileName:     esp32_motor_ctrl_0v1.xdd
      FileVersion:  0V1
      CreationTime: 11:24下午
      CreationDate: 04-12-2023
      CreatedBy:    XUBH
*******************************************************************************/


/*******************************************************************************
   DEVICE INFO:
      VendorName:     XUBH
      VendorNumber:   0x00002
      ProductName:    ESP32_MOTOR_CTRL
      ProductNumber:  0x00001
*******************************************************************************/


/*******************************************************************************
   FEATURES
*******************************************************************************/
  #define CO_NO_SYNC                     1   //Associated objects: 1005-1007
  #define CO_NO_EMERGENCY                1   //Associated objects: 1014, 1015
  #define CO_NO_TIME                     0   //Associated objects: 1012, 1013
  #define CO_NO_SDO_SERVER               1   //Associated objects: 1200-127F
  #define CO_NO_SDO_CLIENT               1   //Associated objects: 1280-12FF
  #define CO_NO_GFC                      0   //Associated objects: 1300
  #define CO_NO_SRDO                     0   //Associated objects: 1301-1341, 1381-13C0
  #define CO_NO_LSS_SERVER               0   //LSS Slave
  #define CO_NO_LSS_CLIENT               0   //LSS Master
  #define CO_NO_RPDO                     4   //Associated objects: 14xx, 16xx
  #define CO_NO_TPDO                     4   //Associated objects: 18xx, 1Axx
  #define CO_NO_NMT_MASTER               1
  #define CO_NO_TRACE                    0


/*******************************************************************************
   OBJECT DICTIONARY
*******************************************************************************/
   #define CO_OD_NoOfElements             78


/*******************************************************************************
   TYPE DEFINITIONS FOR RECORDS
*******************************************************************************/
/*1018      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED32     vendorID;
               UNSIGNED32     productCode;
               UNSIGNED32     revisionNumber;
               UNSIGNED32     serialNumber;
               }              OD_identity_t;
/*1023      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               DOMAIN         command;
               UNSIGNED8      status;
               DOMAIN         reply;
               }              OD_OSCommand_t;
/*1025      */ typedef struct {
               UNSIGNED8      highestSubIndexSupported;
               DOMAIN         command;
               UNSIGNED8      status;
               DOMAIN         reply;
               }              OD_OSDebuggerInterface_t;
/*1200      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED32     COB_IDClientToServer;
               UNSIGNED32     COB_IDServerToClient;
               }              OD_SDOServerParameter_t;
/*1280      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED32     COB_IDClientToServer;
               UNSIGNED32     COB_IDServerToClient;
               UNSIGNED8      nodeIDOfTheSDO_Server;
               }              OD_SDOClientParameter_t;
/*1400      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               UNSIGNED32     COB_IDUsedByRPDO;
               UNSIGNED8      transmissionType;
               }              OD_RPDOCommunicationParameter_t;
/*1600      */ typedef struct {
               UNSIGNED8      numberOfMappedObjects;
               UNSIGNED32     mappedObject1;
               UNSIGNED32     mappedObject2;
               UNSIGNED32     mappedObject3;
               UNSIGNED32     mappedObject4;
               UNSIGNED32     mappedObject5;
               UNSIGNED32     mappedObject6;
               UNSIGNED32     mappedObject7;
               UNSIGNED32     mappedObject8;
               }              OD_RPDOMappingParameter_t;
/*1800      */ typedef struct {
               UNSIGNED8      maxSubIndex;
               UNSIGNED32     COB_IDUsedByTPDO;
               UNSIGNED8      transmissionType;
               UNSIGNED16     inhibitTime;
               UNSIGNED8      compatibilityEntry;
               UNSIGNED16     eventTimer;
               UNSIGNED8      SYNCStartValue;
               }              OD_TPDOCommunicationParameter_t;
/*1A00      */ typedef struct {
               UNSIGNED8      numberOfMappedObjects;
               UNSIGNED32     mappedObject1;
               UNSIGNED32     mappedObject2;
               UNSIGNED32     mappedObject3;
               UNSIGNED32     mappedObject4;
               UNSIGNED32     mappedObject5;
               UNSIGNED32     mappedObject6;
               UNSIGNED32     mappedObject7;
               UNSIGNED32     mappedObject8;
               }              OD_TPDOMappingParameter_t;
/*600F      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED8      externalStopEnable;
               UNSIGNED8      externalStopConfig;
               }              OD_EXTStopParameter_t;
/*6011      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED16     GPIODirection;
               UNSIGNED32     GPIOConfig;
               }              OD_GPIOParameter_t;
/*6013      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED8      ocpth;
               UNSIGNED8      ocpdeg;
               }              OD_OCPParameter_t;
/*6018      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED8      commandNumber;
               UNSIGNED8      offlineAutoRun;
               }              OD_offlineParameter1_t;
/*6019      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED8      commandPointer;
               UNSIGNED32     command;
               UNSIGNED8      saveOfflineCommand;
               }              OD_offlineParameter2_t;
/*602C      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED8      notificationStatus;
               INTEGER32      stepNotificationPosition1;
               INTEGER32      stepNotificationPosition2;
               }              OD_stepPositionNotification_t;
/*602D      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED32     PP_PVModeAcceleration;
               UNSIGNED32     PP_PVModeDeceleration;
               UNSIGNED32     PP_PVModeStartSpeed;
               UNSIGNED32     PP_PVModeStopSpeed;
               }              OD_PP_PVModeParameter1_t;
/*602E      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED16     PP_PVModeControlWord;
               UNSIGNED16     PP_PVModeStatusWord;
               INTEGER32      PP_PVModeRunSpeed;
               INTEGER32      PP_PVModeTargetPosition;
               }              OD_PP_PVModeParameter2_t;
/*602F      */ typedef struct {
               UNSIGNED8      numberOfEntries;
               UNSIGNED8      analogPositioningEnable;
               UNSIGNED16     analogStartAD_Code;
               UNSIGNED16     intervalTimeOfAnalogPositioningAdjustment;
               UNSIGNED16     analogTriggerValue;
               INTEGER32      analogPositioningMinimumPosition;
               INTEGER32      analogPositioningMaximumPosition;
               }              OD_analogPositioningControlParameters_t;

/*******************************************************************************
   TYPE DEFINITIONS FOR OBJECT DICTIONARY INDEXES

   some of those are redundant with CO_SDO.h CO_ObjDicId_t <Common CiA301 object
   dictionary entries>
*******************************************************************************/
/*1000 */
        #define OD_1000_deviceType                                  0x1000

/*1001 */
        #define OD_1001_errorRegister                               0x1001

/*1003 */
        #define OD_1003_preDefinedErrorField                        0x1003

        #define OD_1003_0_preDefinedErrorField_maxSubIndex          0
        #define OD_1003_1_preDefinedErrorField_standardErrorField   1
        #define OD_1003_2_preDefinedErrorField_standardErrorField   2
        #define OD_1003_3_preDefinedErrorField_standardErrorField   3
        #define OD_1003_4_preDefinedErrorField_standardErrorField   4
        #define OD_1003_5_preDefinedErrorField_standardErrorField   5
        #define OD_1003_6_preDefinedErrorField_standardErrorField   6
        #define OD_1003_7_preDefinedErrorField_standardErrorField   7
        #define OD_1003_8_preDefinedErrorField_standardErrorField   8
        #define OD_1003_9_preDefinedErrorField_standardErrorField   9
        #define OD_1003_10_preDefinedErrorField_standardErrorField  10
        #define OD_1003_11_preDefinedErrorField_standardErrorField  11
        #define OD_1003_12_preDefinedErrorField_standardErrorField  12
        #define OD_1003_13_preDefinedErrorField_standardErrorField  13
        #define OD_1003_14_preDefinedErrorField_standardErrorField  14
        #define OD_1003_15_preDefinedErrorField_standardErrorField  15
        #define OD_1003_16_preDefinedErrorField_standardErrorField  16

/*1005 */
        #define OD_1005_COB_ID_SYNCMessage                          0x1005

/*1006 */
        #define OD_1006_communicationCyclePeriod                    0x1006

/*1007 */
        #define OD_1007_synchronousWindowLength                     0x1007

/*1008 */
        #define OD_1008_manufacturerDeviceName                      0x1008

/*1009 */
        #define OD_1009_manufacturerHardwareVersion                 0x1009

/*100A */
        #define OD_100A_manufacturerSoftwareVersion                 0x100A

/*1010 */
        #define OD_1010_storeParameters                             0x1010

        #define OD_1010_0_storeParameters_maxSubIndex               0
        #define OD_1010_1_storeParameters_saveAllParameters         1
        #define OD_1010_2_storeParameters_saveCommunicationParameters 2
        #define OD_1010_3_storeParameters_saveApplicationParameters 3
        #define OD_1010_4_storeParameters_saveManufacturerDefinedParameters 4

/*1011 */
        #define OD_1011_restoreDefaultParameters                    0x1011

        #define OD_1011_0_restoreDefaultParameters_maxSubIndex      0
        #define OD_1011_1_restoreDefaultParameters_restoreAllDefaultParameters 1
        #define OD_1011_2_restoreDefaultParameters_restoreCommunicationDefaultParameters 2
        #define OD_1011_3_restoreDefaultParameters_restoreApplicationDefaultParameters 3
        #define OD_1011_4_restoreDefaultParameters_restoreManufacturerDefinedDefaultParameters 4

/*1014 */
        #define OD_1014_COB_ID_EMCY                                 0x1014

/*1015 */
        #define OD_1015_inhibitTimeEMCY                             0x1015

/*1016 */
        #define OD_1016_consumerHeartbeatTime                       0x1016

        #define OD_1016_0_consumerHeartbeatTime_maxSubIndex         0
        #define OD_1016_1_consumerHeartbeatTime_consumerHeartbeatTime 1
        #define OD_1016_2_consumerHeartbeatTime_consumerHeartbeatTime 2
        #define OD_1016_3_consumerHeartbeatTime_consumerHeartbeatTime 3
        #define OD_1016_4_consumerHeartbeatTime_consumerHeartbeatTime 4
        #define OD_1016_5_consumerHeartbeatTime_consumerHeartbeatTime 5
        #define OD_1016_6_consumerHeartbeatTime_consumerHeartbeatTime 6
        #define OD_1016_7_consumerHeartbeatTime_consumerHeartbeatTime 7
        #define OD_1016_8_consumerHeartbeatTime_consumerHeartbeatTime 8

/*1017 */
        #define OD_1017_producerHeartbeatTime                       0x1017

/*1018 */
        #define OD_1018_identity                                    0x1018

        #define OD_1018_0_identity_maxSubIndex                      0
        #define OD_1018_1_identity_vendorID                         1
        #define OD_1018_2_identity_productCode                      2
        #define OD_1018_3_identity_revisionNumber                   3
        #define OD_1018_4_identity_serialNumber                     4

/*1019 */
        #define OD_1019_synchronousCounterOverflowValue             0x1019

/*1029 */
        #define OD_1029_errorBehavior                               0x1029

        #define OD_1029_0_errorBehavior_maxSubIndex                 0
        #define OD_1029_1_errorBehavior_communicationError          1
        #define OD_1029_2_errorBehavior_profileOrManufacturerSpecificError 2

/*1200 */
        #define OD_1200_SDOServerParameter                          0x1200

        #define OD_1200_0_SDOServerParameter_maxSubIndex            0
        #define OD_1200_1_SDOServerParameter_COB_IDClientToServer   1
        #define OD_1200_2_SDOServerParameter_COB_IDServerToClient   2

/*1280 */
        #define OD_1280_SDOClientParameter                          0x1280

        #define OD_1280_0_SDOClientParameter_maxSubIndex            0
        #define OD_1280_1_SDOClientParameter_COB_IDClientToServer   1
        #define OD_1280_2_SDOClientParameter_COB_IDServerToClient   2
        #define OD_1280_3_SDOClientParameter_nodeIDOfTheSDO_Server  3

/*1400 */
        #define OD_1400_RPDOCommunicationParameter                  0x1400

        #define OD_1400_0_RPDOCommunicationParameter_maxSubIndex    0
        #define OD_1400_1_RPDOCommunicationParameter_COB_IDUsedByRPDO 1
        #define OD_1400_2_RPDOCommunicationParameter_transmissionType 2

/*1401 */
        #define OD_1401_RPDOCommunicationParameter                  0x1401

        #define OD_1401_0_RPDOCommunicationParameter_maxSubIndex    0
        #define OD_1401_1_RPDOCommunicationParameter_COB_IDUsedByRPDO 1
        #define OD_1401_2_RPDOCommunicationParameter_transmissionType 2

/*1402 */
        #define OD_1402_RPDOCommunicationParameter                  0x1402

        #define OD_1402_0_RPDOCommunicationParameter_maxSubIndex    0
        #define OD_1402_1_RPDOCommunicationParameter_COB_IDUsedByRPDO 1
        #define OD_1402_2_RPDOCommunicationParameter_transmissionType 2

/*1403 */
        #define OD_1403_RPDOCommunicationParameter                  0x1403

        #define OD_1403_0_RPDOCommunicationParameter_maxSubIndex    0
        #define OD_1403_1_RPDOCommunicationParameter_COB_IDUsedByRPDO 1
        #define OD_1403_2_RPDOCommunicationParameter_transmissionType 2

/*1600 */
        #define OD_1600_RPDOMappingParameter                        0x1600

        #define OD_1600_0_RPDOMappingParameter_maxSubIndex          0
        #define OD_1600_1_RPDOMappingParameter_mappedObject1        1
        #define OD_1600_2_RPDOMappingParameter_mappedObject2        2
        #define OD_1600_3_RPDOMappingParameter_mappedObject3        3

/*1601 */
        #define OD_1601_RPDOMappingParameter                        0x1601

        #define OD_1601_0_RPDOMappingParameter_maxSubIndex          0
        #define OD_1601_1_RPDOMappingParameter_mappedObject1        1
        #define OD_1601_2_RPDOMappingParameter_mappedObject2        2

/*1602 */
        #define OD_1602_RPDOMappingParameter                        0x1602

        #define OD_1602_0_RPDOMappingParameter_maxSubIndex          0

/*1603 */
        #define OD_1603_RPDOMappingParameter                        0x1603

        #define OD_1603_0_RPDOMappingParameter_maxSubIndex          0
        #define OD_1603_1_RPDOMappingParameter_mappedObject1        1
        #define OD_1603_2_RPDOMappingParameter_mappedObject2        2
        #define OD_1603_3_RPDOMappingParameter_mappedObject3        3
        #define OD_1603_4_RPDOMappingParameter_mappedObject4        4
        #define OD_1603_5_RPDOMappingParameter_mappedObject5        5
        #define OD_1603_6_RPDOMappingParameter_mappedObject6        6
        #define OD_1603_7_RPDOMappingParameter_mappedObject7        7
        #define OD_1603_8_RPDOMappingParameter_mappedObject8        8

/*1800 */
        #define OD_1800_TPDOCommunicationParameter                  0x1800

        #define OD_1800_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1800_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1800_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1800_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1800_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1800_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1800_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1801 */
        #define OD_1801_TPDOCommunicationParameter                  0x1801

        #define OD_1801_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1801_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1801_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1801_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1801_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1801_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1801_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1802 */
        #define OD_1802_TPDOCommunicationParameter                  0x1802

        #define OD_1802_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1802_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1802_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1802_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1802_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1802_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1802_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1803 */
        #define OD_1803_TPDOCommunicationParameter                  0x1803

        #define OD_1803_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1803_1_TPDOCommunicationParameter_COB_IDUsedByTPDO 1
        #define OD_1803_2_TPDOCommunicationParameter_transmissionType 2
        #define OD_1803_3_TPDOCommunicationParameter_inhibitTime    3
        #define OD_1803_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1803_5_TPDOCommunicationParameter_eventTimer     5
        #define OD_1803_6_TPDOCommunicationParameter_SYNCStartValue 6

/*1A00 */
        #define OD_1A00_TPDOMappingParameter                        0x1A00

        #define OD_1A00_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A00_1_TPDOMappingParameter_mappedObject1        1
        #define OD_1A00_2_TPDOMappingParameter_mappedObject2        2
        #define OD_1A00_3_TPDOMappingParameter_mappedObject3        3
        #define OD_1A00_4_TPDOMappingParameter_mappedObject4        4
        #define OD_1A00_5_TPDOMappingParameter_mappedObject5        5
        #define OD_1A00_6_TPDOMappingParameter_mappedObject6        6
        #define OD_1A00_7_TPDOMappingParameter_mappedObject7        7
        #define OD_1A00_8_TPDOMappingParameter_mappedObject8        8

/*1A01 */
        #define OD_1A01_TPDOMappingParameter                        0x1A01

        #define OD_1A01_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A01_1_TPDOMappingParameter_mappedObject1        1
        #define OD_1A01_2_TPDOMappingParameter_mappedObject2        2
        #define OD_1A01_3_TPDOMappingParameter_mappedObject3        3

/*1A02 */
        #define OD_1A02_TPDOMappingParameter                        0x1A02

        #define OD_1A02_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A02_1_TPDOMappingParameter_mappedObject1        1
        #define OD_1A02_2_TPDOMappingParameter_mappedObject2        2

/*1A03 */
        #define OD_1A03_TPDOMappingParameter                        0x1A03

        #define OD_1A03_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A03_1_TPDOMappingParameter_mappedObject1        1

/*1F80 */
        #define OD_1F80_NMTStartup                                  0x1F80

/*1F89 */
        #define OD_1F89_bootTime                                    0x1F89

/*2000 */
        #define OD_2000_errorStatusBits                             0x2000

        #define OD_2000_0_errorStatusBits_maxSubIndex               0
        #define OD_2000_1_errorStatusBits_subObject1                1
        #define OD_2000_2_errorStatusBits_subObject1                2
        #define OD_2000_3_errorStatusBits_subObject1                3
        #define OD_2000_4_errorStatusBits_subObject1                4
        #define OD_2000_5_errorStatusBits_subObject1                5
        #define OD_2000_6_errorStatusBits_subObject1                6
        #define OD_2000_7_errorStatusBits_subObject1                7
        #define OD_2000_8_errorStatusBits_subObject1                8
        #define OD_2000_9_errorStatusBits_subObject1                9
        #define OD_2000_10_errorStatusBits_subObject1               10

/*6000 */
        #define OD_6000_motorStatus                                 0x6000

/*6001 */
        #define OD_6001_controlStatus                               0x6001

/*6002 */
        #define OD_6002_motorDirection                              0x6002

/*6003 */
        #define OD_6003_maxSpeed                                    0x6003

/*6004 */
        #define OD_6004_stepRelativePosition                        0x6004

/*6005 */
        #define OD_6005_workMode                                    0x6005

/*6006 */
        #define OD_6006_startSpeed                                  0x6006

/*6007 */
        #define OD_6007_endSpeed                                    0x6007

/*6008 */
        #define OD_6008_accValue                                    0x6008

/*6009 */
        #define OD_6009_decValue                                    0x6009

/*600A */
        #define OD_600A_microStep                                   0x600A

/*600B */
        #define OD_600B_peakCurrent                                 0x600B

/*600C */
        #define OD_600C_motorPosition                               0x600C

/*600D */
        #define OD_600D_motorEnableRx                               0x600D

/*600E */
        #define OD_600E_motorEnableTx                               0x600E

/*600F */
        #define OD_600F_EXTStopParameter                            0x600F

        #define OD_600F_0_EXTStopParameter_maxSubIndex              0
        #define OD_600F_1_EXTStopParameter_externalStopEnable       1
        #define OD_600F_2_EXTStopParameter_externalStopConfig       2

/*6011 */
        #define OD_6011_GPIOParameter                               0x6011

        #define OD_6011_0_GPIOParameter_maxSubIndex                 0
        #define OD_6011_1_GPIOParameter_GPIODirection               1
        #define OD_6011_2_GPIOParameter_GPIOConfig                  2

/*6012 */
        #define OD_6012_GPIOValue                                   0x6012

/*6013 */
        #define OD_6013_OCPParameter                                0x6013

        #define OD_6013_0_OCPParameter_maxSubIndex                  0
        #define OD_6013_1_OCPParameter_ocpth                        1
        #define OD_6013_2_OCPParameter_ocpdeg                       2

/*6015 */
        #define OD_6015_motionTunning                               0x6015

/*6017 */
        #define OD_6017_stallParameter                              0x6017

/*6018 */
        #define OD_6018_offlineParameter1                           0x6018

        #define OD_6018_0_offlineParameter1_maxSubIndex             0
        #define OD_6018_1_offlineParameter1_commandNumber           1
        #define OD_6018_2_offlineParameter1_offlineAutoRun          2

/*6019 */
        #define OD_6019_offlineParameter2                           0x6019

        #define OD_6019_0_offlineParameter2_maxSubIndex             0
        #define OD_6019_1_offlineParameter2_commandPointer          1
        #define OD_6019_2_offlineParameter2_command                 2
        #define OD_6019_3_offlineParameter2_saveOfflineCommand      3

/*601A */
        #define OD_601A_extStopDebounceDelay                        0x601A

/*601B */
        #define OD_601B_stallConfig                                 0x601B

/*601C */
        #define OD_601C_stepAbsolutePosition                        0x601C

/*6020 */
        #define OD_6020_abortStep                                   0x6020

/*6021 */
        #define OD_6021_linesPerRev                                 0x6021

/*6026 */
        #define OD_6026_thePositionEaBetweenPulseCountAndRealCount  0x6026

/*6027 */
        #define OD_6027_adjustValueUsedToRecoverSpeedFromStall      0x6027

/*6028 */
        #define OD_6028_stallLength                                 0x6028

/*6029 */
        #define OD_6029_torqueLoopEnable                            0x6029

/*602A */
        #define OD_602A_powerOffSavePositionEnable                  0x602A

/*602B */
        #define OD_602B_analogInputAdCode                           0x602B

/*602C */
        #define OD_602C_stepPositionNotification                    0x602C

        #define OD_602C_0_stepPositionNotification_maxSubIndex      0
        #define OD_602C_1_stepPositionNotification_notificationStatus 1
        #define OD_602C_2_stepPositionNotification_stepNotificationPosition1 2
        #define OD_602C_3_stepPositionNotification_stepNotificationPosition2 3

/*602D */
        #define OD_602D_PP_PVModeParameter1                         0x602D

        #define OD_602D_0_PP_PVModeParameter1_maxSubIndex           0
        #define OD_602D_1_PP_PVModeParameter1_PP_PVModeAcceleration 1
        #define OD_602D_2_PP_PVModeParameter1_PP_PVModeDeceleration 2
        #define OD_602D_3_PP_PVModeParameter1_PP_PVModeStartSpeed   3
        #define OD_602D_4_PP_PVModeParameter1_PP_PVModeStopSpeed    4

/*602E */
        #define OD_602E_PP_PVModeParameter2                         0x602E

        #define OD_602E_0_PP_PVModeParameter2_maxSubIndex           0
        #define OD_602E_1_PP_PVModeParameter2_PP_PVModeControlWord  1
        #define OD_602E_2_PP_PVModeParameter2_PP_PVModeStatusWord   2
        #define OD_602E_3_PP_PVModeParameter2_PP_PVModeRunSpeed     3
        #define OD_602E_4_PP_PVModeParameter2_PP_PVModeTargetPosition 4

/*602F */
        #define OD_602F_analogPositioningControlParameters          0x602F

        #define OD_602F_0_analogPositioningControlParameters_maxSubIndex 0
        #define OD_602F_1_analogPositioningControlParameters_analogPositioningEnable 1
        #define OD_602F_2_analogPositioningControlParameters_analogStartAD_Code 2
        #define OD_602F_3_analogPositioningControlParameters_intervalTimeOfAnalogPositioningAdjustment 3
        #define OD_602F_4_analogPositioningControlParameters_analogTriggerValue 4
        #define OD_602F_5_analogPositioningControlParameters_analogPositioningMinimumPosition 5
        #define OD_602F_6_analogPositioningControlParameters_analogPositioningMaximumPosition 6

/*6030 */
        #define OD_6030_realTimeSpeed                               0x6030

/*******************************************************************************
   STRUCTURES FOR VARIABLES IN DIFFERENT MEMORY LOCATIONS
*******************************************************************************/
#define  CO_OD_FIRST_LAST_WORD     0x55 //Any value from 0x01 to 0xFE. If changed, EEPROM will be reinitialized.

/***** Structure for RAM variables ********************************************/
struct sCO_OD_RAM{
               UNSIGNED32     FirstWord;

/*1000      */ UNSIGNED32     deviceType;
/*1001      */ UNSIGNED8      errorRegister;
/*1003      */ UNSIGNED32      preDefinedErrorField[16];
/*1005      */ UNSIGNED32     COB_ID_SYNCMessage;
/*1006      */ UNSIGNED32     communicationCyclePeriod;
/*1008      */ VISIBLE_STRING manufacturerDeviceName[1];
/*1009      */ VISIBLE_STRING manufacturerHardwareVersion[1];
/*100A      */ VISIBLE_STRING manufacturerSoftwareVersion[1];
/*1010      */ UNSIGNED32      storeParameters[4];
/*1011      */ UNSIGNED32      restoreDefaultParameters[4];
/*1017      */ UNSIGNED16     producerHeartbeatTime;
/*1018      */ OD_identity_t   identity;
/*1200      */ OD_SDOServerParameter_t SDOServerParameter[1];
/*1280      */ OD_SDOClientParameter_t SDOClientParameter[1];
/*1400      */ OD_RPDOCommunicationParameter_t RPDOCommunicationParameter[4];
/*1600      */ OD_RPDOMappingParameter_t RPDOMappingParameter[4];
/*1800      */ OD_TPDOCommunicationParameter_t TPDOCommunicationParameter[4];
/*1A00      */ OD_TPDOMappingParameter_t TPDOMappingParameter[4];
/*1F80      */ UNSIGNED32     NMTStartup;
/*1F89      */ UNSIGNED32     bootTime;
/*2000      */ UNSIGNED8       errorStatusBits[10];
/*6000      */ UNSIGNED8      motorStatus;
/*6001      */ UNSIGNED8      controlStatus;
/*6002      */ UNSIGNED8      motorDirection;
/*6003      */ UNSIGNED32     maxSpeed;
/*6004      */ INTEGER32      stepRelativePosition;
/*6005      */ UNSIGNED8      workMode;
/*6006      */ UNSIGNED16     startSpeed;
/*6007      */ UNSIGNED16     endSpeed;
/*6008      */ UNSIGNED8      accValue;
/*6009      */ UNSIGNED8      decValue;
/*600A      */ UNSIGNED16     microStep;
/*600B      */ UNSIGNED16     peakCurrent;
/*600C      */ INTEGER32      motorPosition;
/*600D      */ UNSIGNED8      motorEnableRx;
/*600E      */ UNSIGNED8      motorEnableTx;
/*600F      */ OD_EXTStopParameter_t EXTStopParameter;
/*6011      */ OD_GPIOParameter_t GPIOParameter;
/*6012      */ UNSIGNED16     GPIOValue;
/*6013      */ OD_OCPParameter_t OCPParameter;
/*6015      */ UNSIGNED32     motionTunning;
/*6017      */ UNSIGNED16     stallParameter;
/*6018      */ OD_offlineParameter1_t offlineParameter1;
/*6019      */ OD_offlineParameter2_t offlineParameter2;
/*601A      */ UNSIGNED16     extStopDebounceDelay;
/*601B      */ UNSIGNED8      stallConfig;
/*601C      */ INTEGER32      stepAbsolutePosition;
/*6020      */ UNSIGNED8      abortStep;
/*6021      */ UNSIGNED16     linesPerRev;
/*6026      */ INTEGER8       thePositionEaBetweenPulseCountAndRealCount;
/*6027      */ UNSIGNED8      adjustValueUsedToRecoverSpeedFromStall;
/*6028      */ INTEGER16      stallLength;
/*6029      */ UNSIGNED8      torqueLoopEnable;
/*602A      */ UNSIGNED8      powerOffSavePositionEnable;
/*602B      */ UNSIGNED16     analogInputAdCode;
/*602C      */ OD_stepPositionNotification_t stepPositionNotification;
/*602D      */ OD_PP_PVModeParameter1_t PP_PVModeParameter1;
/*602E      */ OD_PP_PVModeParameter2_t PP_PVModeParameter2;
/*602F      */ OD_analogPositioningControlParameters_t analogPositioningControlParameters;
/*6030      */ INTEGER32      realTimeSpeed;

               UNSIGNED32     LastWord;
};

/***** Structure for ROM variables ********************************************/
struct sCO_OD_ROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for EEPROM variables ********************************************/
struct sCO_OD_EEPROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for PERSIST_COMM variables ********************************************/
struct sCO_OD_PERSIST_COMM{
               UNSIGNED32     FirstWord;

/*1007      */ UNSIGNED32     synchronousWindowLength;
/*1014      */ UNSIGNED32     COB_ID_EMCY;
/*1015      */ UNSIGNED16     inhibitTimeEMCY;
/*1016      */ UNSIGNED32      consumerHeartbeatTime[8];
/*1019      */ UNSIGNED8      synchronousCounterOverflowValue;
/*1029      */ UNSIGNED8       errorBehavior[2];

               UNSIGNED32     LastWord;
};

/***** Declaration of Object Dictionary variables *****************************/
extern struct sCO_OD_RAM CO_OD_RAM;

extern struct sCO_OD_ROM CO_OD_ROM;

extern struct sCO_OD_EEPROM CO_OD_EEPROM;

extern struct sCO_OD_PERSIST_COMM CO_OD_PERSIST_COMM;

/*******************************************************************************
   ALIASES FOR OBJECT DICTIONARY VARIABLES
*******************************************************************************/
/*1000, Data Type: UNSIGNED32 */
        #define OD_deviceType                                       CO_OD_RAM.deviceType

/*1001, Data Type: UNSIGNED8 */
        #define OD_errorRegister                                    CO_OD_RAM.errorRegister

/*1003, Data Type: UNSIGNED32, Array[16] */
        #define OD_preDefinedErrorField                             CO_OD_RAM.preDefinedErrorField
        #define ODL_preDefinedErrorField_arrayLength                16
        #define ODA_preDefinedErrorField_standardErrorField         0

/*1005, Data Type: UNSIGNED32 */
        #define OD_COB_ID_SYNCMessage                               CO_OD_RAM.COB_ID_SYNCMessage

/*1006, Data Type: UNSIGNED32 */
        #define OD_communicationCyclePeriod                         CO_OD_RAM.communicationCyclePeriod

/*1007, Data Type: UNSIGNED32 */
        #define OD_synchronousWindowLength                          CO_OD_PERSIST_COMM.synchronousWindowLength

/*1008, Data Type: VISIBLE_STRING */
        #define OD_manufacturerDeviceName                           CO_OD_RAM.manufacturerDeviceName
        #define ODL_manufacturerDeviceName_stringLength             1

/*1009, Data Type: VISIBLE_STRING */
        #define OD_manufacturerHardwareVersion                      CO_OD_RAM.manufacturerHardwareVersion
        #define ODL_manufacturerHardwareVersion_stringLength        1

/*100A, Data Type: VISIBLE_STRING */
        #define OD_manufacturerSoftwareVersion                      CO_OD_RAM.manufacturerSoftwareVersion
        #define ODL_manufacturerSoftwareVersion_stringLength        1

/*1010, Data Type: UNSIGNED32, Array[4] */
        #define OD_storeParameters                                  CO_OD_RAM.storeParameters
        #define ODL_storeParameters_arrayLength                     4
        #define ODA_storeParameters_saveAllParameters               0
        #define ODA_storeParameters_saveCommunicationParameters     1
        #define ODA_storeParameters_saveApplicationParameters       2
        #define ODA_storeParameters_saveManufacturerDefinedParameters 3

/*1011, Data Type: UNSIGNED32, Array[4] */
        #define OD_restoreDefaultParameters                         CO_OD_RAM.restoreDefaultParameters
        #define ODL_restoreDefaultParameters_arrayLength            4
        #define ODA_restoreDefaultParameters_restoreAllDefaultParameters 0
        #define ODA_restoreDefaultParameters_restoreCommunicationDefaultParameters 1
        #define ODA_restoreDefaultParameters_restoreApplicationDefaultParameters 2
        #define ODA_restoreDefaultParameters_restoreManufacturerDefinedDefaultParameters 3

/*1014, Data Type: UNSIGNED32 */
        #define OD_COB_ID_EMCY                                      CO_OD_PERSIST_COMM.COB_ID_EMCY

/*1015, Data Type: UNSIGNED16 */
        #define OD_inhibitTimeEMCY                                  CO_OD_PERSIST_COMM.inhibitTimeEMCY

/*1016, Data Type: UNSIGNED32, Array[8] */
        #define OD_consumerHeartbeatTime                            CO_OD_PERSIST_COMM.consumerHeartbeatTime
        #define ODL_consumerHeartbeatTime_arrayLength               8
        #define ODA_consumerHeartbeatTime_consumerHeartbeatTime     0

/*1017, Data Type: UNSIGNED16 */
        #define OD_producerHeartbeatTime                            CO_OD_RAM.producerHeartbeatTime

/*1018, Data Type: identity_t */
        #define OD_identity                                         CO_OD_RAM.identity

/*1019, Data Type: UNSIGNED8 */
        #define OD_synchronousCounterOverflowValue                  CO_OD_PERSIST_COMM.synchronousCounterOverflowValue

/*1029, Data Type: UNSIGNED8, Array[2] */
        #define OD_errorBehavior                                    CO_OD_PERSIST_COMM.errorBehavior
        #define ODL_errorBehavior_arrayLength                       2
        #define ODA_errorBehavior_communicationError                0
        #define ODA_errorBehavior_profileOrManufacturerSpecificError 1

/*1200, Data Type: SDOServerParameter_t */
        #define OD_SDOServerParameter                               CO_OD_RAM.SDOServerParameter

/*1280, Data Type: SDOClientParameter_t */
        #define OD_SDOClientParameter                               CO_OD_RAM.SDOClientParameter

/*1400, Data Type: RPDOCommunicationParameter_t */
        #define OD_RPDOCommunicationParameter                       CO_OD_RAM.RPDOCommunicationParameter

/*1600, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter                             CO_OD_RAM.RPDOMappingParameter

/*1800, Data Type: TPDOCommunicationParameter_t */
        #define OD_TPDOCommunicationParameter                       CO_OD_RAM.TPDOCommunicationParameter

/*1A00, Data Type: TPDOMappingParameter_t */
        #define OD_TPDOMappingParameter                             CO_OD_RAM.TPDOMappingParameter

/*1F80, Data Type: UNSIGNED32 */
        #define OD_NMTStartup                                       CO_OD_RAM.NMTStartup

/*1F89, Data Type: UNSIGNED32 */
        #define OD_bootTime                                         CO_OD_RAM.bootTime

/*2000, Data Type: UNSIGNED8, Array[10] */
        #define OD_errorStatusBits                                  CO_OD_RAM.errorStatusBits
        #define ODL_errorStatusBits_arrayLength                     10
        #define ODA_errorStatusBits_subObject1                      0

/*6000, Data Type: UNSIGNED8 */
        #define OD_motorStatus                                      CO_OD_RAM.motorStatus

/*6001, Data Type: UNSIGNED8 */
        #define OD_controlStatus                                    CO_OD_RAM.controlStatus

/*6002, Data Type: UNSIGNED8 */
        #define OD_motorDirection                                   CO_OD_RAM.motorDirection

/*6003, Data Type: UNSIGNED32 */
        #define OD_maxSpeed                                         CO_OD_RAM.maxSpeed

/*6004, Data Type: INTEGER32 */
        #define OD_stepRelativePosition                             CO_OD_RAM.stepRelativePosition

/*6005, Data Type: UNSIGNED8 */
        #define OD_workMode                                         CO_OD_RAM.workMode

/*6006, Data Type: UNSIGNED16 */
        #define OD_startSpeed                                       CO_OD_RAM.startSpeed

/*6007, Data Type: UNSIGNED16 */
        #define OD_endSpeed                                         CO_OD_RAM.endSpeed

/*6008, Data Type: UNSIGNED8 */
        #define OD_accValue                                         CO_OD_RAM.accValue

/*6009, Data Type: UNSIGNED8 */
        #define OD_decValue                                         CO_OD_RAM.decValue

/*600A, Data Type: UNSIGNED16 */
        #define OD_microStep                                        CO_OD_RAM.microStep

/*600B, Data Type: UNSIGNED16 */
        #define OD_peakCurrent                                      CO_OD_RAM.peakCurrent

/*600C, Data Type: INTEGER32 */
        #define OD_motorPosition                                    CO_OD_RAM.motorPosition

/*600D, Data Type: UNSIGNED8 */
        #define OD_motorEnableRx                                    CO_OD_RAM.motorEnableRx

/*600E, Data Type: UNSIGNED8 */
        #define OD_motorEnableTx                                    CO_OD_RAM.motorEnableTx

/*600F, Data Type: EXTStopParameter_t */
        #define OD_EXTStopParameter                                 CO_OD_RAM.EXTStopParameter

/*6011, Data Type: GPIOParameter_t */
        #define OD_GPIOParameter                                    CO_OD_RAM.GPIOParameter

/*6012, Data Type: UNSIGNED16 */
        #define OD_GPIOValue                                        CO_OD_RAM.GPIOValue

/*6013, Data Type: OCPParameter_t */
        #define OD_OCPParameter                                     CO_OD_RAM.OCPParameter

/*6015, Data Type: UNSIGNED32 */
        #define OD_motionTunning                                    CO_OD_RAM.motionTunning

/*6017, Data Type: UNSIGNED16 */
        #define OD_stallParameter                                   CO_OD_RAM.stallParameter

/*6018, Data Type: offlineParameter1_t */
        #define OD_offlineParameter1                                CO_OD_RAM.offlineParameter1

/*6019, Data Type: offlineParameter2_t */
        #define OD_offlineParameter2                                CO_OD_RAM.offlineParameter2

/*601A, Data Type: UNSIGNED16 */
        #define OD_extStopDebounceDelay                             CO_OD_RAM.extStopDebounceDelay

/*601B, Data Type: UNSIGNED8 */
        #define OD_stallConfig                                      CO_OD_RAM.stallConfig

/*601C, Data Type: INTEGER32 */
        #define OD_stepAbsolutePosition                             CO_OD_RAM.stepAbsolutePosition

/*6020, Data Type: UNSIGNED8 */
        #define OD_abortStep                                        CO_OD_RAM.abortStep

/*6021, Data Type: UNSIGNED16 */
        #define OD_linesPerRev                                      CO_OD_RAM.linesPerRev

/*6026, Data Type: INTEGER8 */
        #define OD_thePositionEaBetweenPulseCountAndRealCount       CO_OD_RAM.thePositionEaBetweenPulseCountAndRealCount

/*6027, Data Type: UNSIGNED8 */
        #define OD_adjustValueUsedToRecoverSpeedFromStall           CO_OD_RAM.adjustValueUsedToRecoverSpeedFromStall

/*6028, Data Type: INTEGER16 */
        #define OD_stallLength                                      CO_OD_RAM.stallLength

/*6029, Data Type: UNSIGNED8 */
        #define OD_torqueLoopEnable                                 CO_OD_RAM.torqueLoopEnable

/*602A, Data Type: UNSIGNED8 */
        #define OD_powerOffSavePositionEnable                       CO_OD_RAM.powerOffSavePositionEnable

/*602B, Data Type: UNSIGNED16 */
        #define OD_analogInputAdCode                                CO_OD_RAM.analogInputAdCode

/*602C, Data Type: stepPositionNotification_t */
        #define OD_stepPositionNotification                         CO_OD_RAM.stepPositionNotification

/*602D, Data Type: PP_PVModeParameter1_t */
        #define OD_PP_PVModeParameter1                              CO_OD_RAM.PP_PVModeParameter1

/*602E, Data Type: PP_PVModeParameter2_t */
        #define OD_PP_PVModeParameter2                              CO_OD_RAM.PP_PVModeParameter2

/*602F, Data Type: analogPositioningControlParameters_t */
        #define OD_analogPositioningControlParameters               CO_OD_RAM.analogPositioningControlParameters

/*6030, Data Type: INTEGER32 */
        #define OD_realTimeSpeed                                    CO_OD_RAM.realTimeSpeed

#endif
// clang-format on
